---
title: "quinn-1999"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{quinn-1999}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(quinn.myopia)
load_all()
```

```{r}
library(ggplot2)
myopia %>% # Data set piped into...
  ggplot(aes(x = Sight)) + # This specifies the variable
  geom_bar(stat = "count") + # Tell it to make a bar plot
  labs(title = "Frequency Bar Plot of Level of Myopia", # Give your plot a title
       x = "Level of Myopia", # Label the x axis
       y = "Frequency") # Label the y axis

```


```{r}
library(dplyr)
myopia = 
  myopia |> 
  mutate(
    myopic = Sight %in% c("Myopia", "High Myopia"),
    Light = Light |> 
      factor(
        levels = c("No Light", "Nightlight", "Full Light"),
        ordered = FALSE),
    Sight = Sight |> 
      factor(
        levels = c("No Myopia" , "Myopia", "High Myopia"),
        ordered = TRUE)
  ) 

```

```{r}
myopia |> select(Light, Sight) |> table()

```


```{r}
myopia |> ggplot(aes(x = Light, fill = Sight)) +
  geom_bar(position = "fill")
```


```{r}

glm1 = glm(family = binomial(link = 'identity'), data = myopia,
           formula =  myopic ~ Light)

library(parameters)

parameters(glm1)

```


Some discussion: [https://www.nei.nih.gov/about/news-and-events/news/myopia-development-and-nighttime-light-exposure-infancy]

Response from original authors:

[https://www.nature.com/articles/35004665]
